### ISSUE TITLE
Core - scope apply

### ISSUE THREAD

**Issue by dud3** [Drooids/olm#11]
There's something wrong with `$scope.$apply()` all over the code base.
## Example error

``` js
Error: [$rootScope:inprog] http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24apply
    at Error (native)
    at http://localhost/olm/js/angular.min.js:6:417
    at p (http://localhost/olm/js/angular.min.js:118:370)
    at n.$get.n.$apply (http://localhost/olm/js/angular.min.js:126:224)
    at klass.TransformController.onObjectSelect (http://localhost/olm/js/olm.js?v=0.134:730:22)
    at klass.fire (http://localhost/olm/js/fabric.js:1:1990)
    at klass.fabric.Canvas.fabric.util.createClass.setActiveObject (http://localhost/olm/js/fabric.js:5:20885)
    at CanvasService.select (http://localhost/olm/js/olm.js?v=0.134:1876:19)
    at CanvasService.add (http://localhost/olm/js/olm.js?v=0.134:1863:14)
    at Command.run (http://localhost/olm/js/olm.js?v=0.134:97:18)
```

**Comment by dud3** [comment]
Investigate why.
